# colors normal
# black
palette = 0=#222
# red
palette = 1=#e11
# green
palette = 2=#6e1
# yellow
palette = 3=#eb1
# blue
palette = 4=#16e
# magenta
palette = 5=#85e
# cyan
palette = 6=#1de
# white
palette = 7=#eee

# colors bright
# black
palette = 8=#555
# red
palette = 9=#f55
# green
palette = 10=#bf7
# yellow
palette = 11=#fd7
# blue
palette = 12=#0af
# magenta
palette = 13=#a8f
# cyan
palette = 14=#7ef
# white
palette = 15=#fff


background = "#000000"
foreground = "#FFFFFF"
