[colors]
transparent_background_colors = true

[colors.bright]
black = "#444444"
red = "#ff273f"
green = "#abe05a"
yellow = "#ffd141"
blue = "#0092ff"
magenta = "#9a5feb"
cyan = "#67ffef"
white = "#ffffff"

[colors.normal]
black = "#222222"
red = "#ff000f"
green = "#8ce00a"
yellow = "#ffb900"
blue = "#008df8"
magenta = "#8d56d6"
cyan = "#00d7eb"
white = "#ffffff"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"
